Repository Mantecao-EGC/mantecao-hub, pull requests merged in 2024-12, with the labels that each got.

#21 feat: Testeo Selenium de remember me
  app/modules/auth/tests/test_selenium.py
Labels: feature

#29 Feat 22/ Mejorar la interfaz de usuario
  app/modules/dataset/templates/dataset/view_dataset.html
Labels: enhancement

#30 Feat-27/Add release workflow
  .github/workflows/release.yml
Labels: enhancement

#37 Feat-25/Add dockerhub workflow
  .github/workflows/dockerhub.yml
Labels: feature

#36 Feat 31/fakenodo
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/routes.py
  app/modules/dataset/templates/dataset/upload_dataset.html
  app/modules/fakenodo/__init__.py
  app/modules/fakenodo/forms.py
  app/modules/fakenodo/models.py
  app/modules/fakenodo/repositories.py
  app/modules/fakenodo/routes.py
  app/modules/fakenodo/seeders.py
  app/modules/fakenodo/services.py
  app/modules/fakenodo/tests/__init__.py
  app/modules/fakenodo/tests/locustfile.py
  app/modules/fakenodo/tests/test_unit.py
  core/configuration/configuration.py
Labels: feature

#41 Feat 23/filtros avanzados
  app/modules/dataset/models.py
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/routes.py
  app/modules/explore/services.py
  app/modules/explore/templates/explore/index.html
Labels: feature

#42 Fix-39/Arreglar el workflow de las releases
  .github/workflows/release.yml
Labels: fix

#45 Fix-39/Arreglar el workflow de las releases UPDATED
  .github/workflows/release.yml
Labels: fix

#46 Fix-39/Arreglar el workflow de las releases
  .github/workflows/release.yml
Labels: fix

#47 Fix-39/Arreglar el workflow de las releases
  .github/workflows/release.yml
Labels: fix

#48 Feat 43/view user profile
  app/modules/dataset/repositories.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/profile/services.py
  app/modules/profile/templates/profile/view_profile.html
  app/modules/public/routes.py
Labels: feature

#49 Enhancement-38/Testing profile
  app/modules/profile/routes.py
  app/modules/profile/tests/locustfile.py
  app/modules/profile/tests/test_selenium.py
  app/modules/profile/tests/test_unit.py
Labels: enhancement

#56 Fix 54/is_developer no debe ser un campo obligatorio
  app/modules/auth/services.py
Labels: fix

#53 Enhancement 44/testing filtros avanzados
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_selenium.py
Labels: enhancement

#59 Fix-55/Elimnación y corrección de tests actuales
  app/modules/auth/tests/test_unit.py
Labels: fix

#57 Fix-52/Fakenodo no publica los datasets con DOI
  app/modules/dataset/assets/scripts.js
  app/modules/dataset/forms.py
  app/modules/dataset/routes.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/templates/dataset/upload_dataset.html
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/fakenodo/assets/scripts.js
  app/modules/fakenodo/models.py
  app/modules/fakenodo/seeders.py
  app/modules/fakenodo/services.py
  app/modules/zenodo/.env.example
  app/modules/zenodo/__init__.py
  app/modules/zenodo/assets/scripts.js
  app/modules/zenodo/forms.py
  app/modules/zenodo/models.py
  app/modules/zenodo/repositories.py
  app/modules/zenodo/routes.py
  app/modules/zenodo/services.py
  app/modules/zenodo/templates/zenodo/index.html
  core/configuration/configuration.py
  migrations/versions/a1abf9d5dc7d_.py
Labels: fix

#51 Feat 24/busqueda de modelos avanzada
  app/modules/conftest.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/explore/repositories.py
  requirements.txt
Labels: feature

#60 Enhancement 58/testing de auth
  app/modules/auth/tests/test_unit.py
Labels: enhancement

#61 Enhancement 32/testing fakenodo
  app/modules/fakenodo/tests/locustfile.py
  app/modules/fakenodo/tests/test_unit.py
Labels: enhancement

#62 Feat 26/documentacion del proyecto
  docs/working-policies.md
Labels: documentation

#64 Feat-63/Icono-desarrollador
  app/modules/profile/templates/profile/summary.html
  app/modules/profile/templates/profile/view_profile.html
Labels: feature
