Repository Mantecao-EGC/mantecao-hub, pull requests merged in 2024-11, with the labels that each got.

#11 Feat 8/registrarse como desarrollador
  app/modules/auth/forms.py
  app/modules/auth/models.py
  app/modules/auth/seeders.py
  app/modules/auth/services.py
  app/modules/auth/templates/auth/signup_form.html
  app/modules/profile/templates/profile/summary.html
  app/modules/public/templates/public/index.html
Labels: feature

#12 Develop
  .github/ISSUE_TEMPLATE/FEAT.yml
  docs/images/FlowDiagram.jpg
  docs/working-policies.md
Labels: documentation

#16 Feat 13/testing para m2 de 8
  app/modules/auth/services.py
  app/modules/auth/tests/locustfile.py
  app/modules/auth/tests/test_selenium.py
  app/modules/auth/tests/test_unit.py
  app/modules/conftest.py
  app/modules/profile/tests/test_unit.py
Labels: feature

#15 Feat 7/mejor motor de busqueda
  .github/workflows/codacy.yml
  app/modules/explore/assets/scripts.js
  app/modules/explore/templates/explore/index.html
  migrations/versions/9477f060995a_.py
  migrations/versions/f2a3b207b3eb_.py
Labels: feature

#18 Fix 17/test de selenium de auth
  app/modules/auth/services.py
  app/modules/auth/tests/test_selenium.py
  core/selenium/common.py
Labels: fix
